Towards payloads on tags and args/return values for continuations
effect-handlers/wasmtime pull request #28
Opened 2023-06-05 16:21 UTC by frank-emrich

This PR is built on top of #25.

Things that should work:
- when `suspend`-ing, can now pass a single i32 value to the tag (i.e.,  handler)
- in handler blocks, can now correspondingly receive a single i32 value as payload
-  switching logic for handling different tags given in a `resume` instruction and receiving the aforementioned payloads in the handler blocks associated with each tag
- when continuing, can receive a single i32 value back at the suspend site
- when a continuation returns ordinarily, can return a single i32 value

Things that do not work:
- Passing a value to a continuation obtained from cont.new rather than a handler.

All of this is tested in the new file `cont_resume2.wast`.

2023-06-06 15:40 UTC, dhil requested changes
LGTM.

2023-06-06 15:40 UTC, dhil commented on cranelift/wasm/src/func_translator.rs
> +    println!("func: {:?}", builder.func);
Comment/remove.

2023-06-06 15:40 UTC, dhil commented on tests/all/pooling_allocator.rs
> + * 5.88% - 16 bytes - jit store state
Needs to say
```
instance allocation for this module requires 320 bytes which exceeds the \
configured maximum of 16 bytes; breakdown of allocation requirement:

 * 55.00% - 176 bytes - instance state management
 * 15.00% - 48 bytes - typed continuations payloads
```

2023-06-06 15:40 UTC, dhil commented on tests/all/pooling_allocator.rs
> + * 85.47% - 1600 bytes - defined globals
Needs to say
```
instance allocation for this module requires 1920 bytes which exceeds the \
configured maximum of 16 bytes; breakdown of allocation requirement:

 * 9.17% - 176 bytes - instance state management
 * 83.33% - 1600 bytes - defined globals
```

2023-06-06 15:40 UTC, dhil commented on cranelift/wasm/src/code_translator.rs
> +
```suggestion
```

2023-06-06 15:40 UTC, dhil commented on cranelift/wasm/src/code_translator.rs
> +                builder.ins().trap(ir::TrapCode::UnreachableCodeReached);
```suggestion
                // TODO: emit effect forwarding logic.
                builder.ins().trap(ir::TrapCode::UnreachableCodeReached);
```

2023-06-06 15:40 UTC, dhil commented on cranelift/wasm/src/code_translator.rs
> +                // exactly one argument to the return block above!
```suggestion
```
Stale comment I suppose?

2023-06-06 15:40 UTC, dhil commented on cranelift/wasm/src/code_translator.rs
> +            //translate_operator(validator, &Operator::Drop, builder, state, environ)?;
This comment can be removed.

2023-06-08 10:55 UTC, frank-emrich commented on tests/all/pooling_allocator.rs
> + * 5.88% - 16 bytes - jit store state
Why not mention the typed continuations store anymore? in the `VMContext`, we distinguish between the continuations store and the payloads?

2023-06-08 10:58 UTC, frank-emrich commented on cranelift/wasm/src/code_translator.rs
> +            //translate_operator(validator, &Operator::Drop, builder, state, environ)?;
Do you mean the entire ~100 line comment?

2023-06-08 11:20 UTC, dhil approved these changes

2023-06-08 11:20 UTC, dhil commented on cranelift/wasm/src/code_translator.rs
> +            //translate_operator(validator, &Operator::Drop, builder, state, environ)?;
Yes. Lets get rid of it.

2023-06-08 11:21 UTC, dhil commented on tests/all/pooling_allocator.rs
> + * 5.88% - 16 bytes - jit store state
Because the test wont pass then... The test is sensitive to the layout of `VMContext`. So we just write whatever makes this test pass.

2023-06-08 11:22 UTC, dhil commented on tests/all/pooling_allocator.rs
> + * 5.88% - 16 bytes - jit store state
Alternatively, we remove this particular test as it is somewhat annoying and irrelevant.

2023-06-08 11:23 UTC, dhil commented
We need to tinker a bit with the CI. We should probably do that in a separate PR though, so we can just forcibly squash'n'merge this one when you are ready.

2023-06-08 13:59 UTC, frank-emrich commented on tests/all/pooling_allocator.rs
> + * 5.88% - 16 bytes - jit store state
Okay, I overlooked that these are actually generated messages.

2023-06-08 15:39 UTC, merged